### ISSUE TITLE
Blackscreens on Dual Monitor Setup when clicking out of the Gamewindow (or alt-tabbing)

### ISSUE THREAD

**Issue by plamf** [pepopo978/SuperwowInstallation#1]
After installing Superwow, I get 2-3 sec Blackscreens on both my Monitors each time I click out and back into the game.
Any idea why?

**Comment by pepopo978** [comment]
try adding 
`d3d9.enableDialogMode = True`
to your dxvk.conf

**Comment by plamf** [comment]
Thanks, that worked!
